services:
  kollabium_notification:
    build: .
    restart: always
    env_file:
      - src/.env-non-dev
    volumes:
      - .:/app
    command: >
      sh -c "
      cd ./src/ &&
      uv run faststream run main:fs --host 0.0.0.0
      "

  nats: 
    image: nats:latest
    restart: always
    ports:
      - "4222:4222"
      # - "6222:6222"
      - "8222:8222"
    volumes:
      - nats_data:/data

volumes:
  nats_data:
    driver: local